//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class page {
    
    private pageTabInfo[] tabInfoField;
    
    private pageGuildInfo[] guildInfoField;
    
    private string globalSearchField;
    
    private string langField;
    
    private string requestUrlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tabInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public pageTabInfo[] tabInfo {
        get {
            return this.tabInfoField;
        }
        set {
            this.tabInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("guildInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public pageGuildInfo[] guildInfo {
        get {
            return this.guildInfoField;
        }
        set {
            this.guildInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string globalSearch {
        get {
            return this.globalSearchField;
        }
        set {
            this.globalSearchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string requestUrl {
        get {
            return this.requestUrlField;
        }
        set {
            this.requestUrlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class pageTabInfo {
    
    private string subTabField;
    
    private string tabField;
    
    private string tabGroupField;
    
    private string tabUrlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string subTab {
        get {
            return this.subTabField;
        }
        set {
            this.subTabField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tab {
        get {
            return this.tabField;
        }
        set {
            this.tabField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tabGroup {
        get {
            return this.tabGroupField;
        }
        set {
            this.tabGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tabUrl {
        get {
            return this.tabUrlField;
        }
        set {
            this.tabUrlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class pageGuildInfo {
    
    private pageGuildInfoGuildHeader[] guildHeaderField;
    
    private pageGuildInfoGuildMessages[] guildMessagesField;
    
    private pageGuildInfoGuildRanksRank[] guildRanksField;
    
    private pageGuildInfoGuildBank[] guildBankField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("guildHeader", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public pageGuildInfoGuildHeader[] guildHeader {
        get {
            return this.guildHeaderField;
        }
        set {
            this.guildHeaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("guildMessages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public pageGuildInfoGuildMessages[] guildMessages {
        get {
            return this.guildMessagesField;
        }
        set {
            this.guildMessagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("rank", typeof(pageGuildInfoGuildRanksRank), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public pageGuildInfoGuildRanksRank[] guildRanks {
        get {
            return this.guildRanksField;
        }
        set {
            this.guildRanksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("guildBank", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public pageGuildInfoGuildBank[] guildBank {
        get {
            return this.guildBankField;
        }
        set {
            this.guildBankField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class pageGuildInfoGuildHeader {
    
    private pageGuildInfoGuildHeaderEmblem[] emblemField;
    
    private string battleGroupField;
    
    private string countField;
    
    private string factionField;
    
    private string nameField;
    
    private string nameUrlField;
    
    private string realmField;
    
    private string realmUrlField;
    
    private string urlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("emblem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public pageGuildInfoGuildHeaderEmblem[] emblem {
        get {
            return this.emblemField;
        }
        set {
            this.emblemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string battleGroup {
        get {
            return this.battleGroupField;
        }
        set {
            this.battleGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string faction {
        get {
            return this.factionField;
        }
        set {
            this.factionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nameUrl {
        get {
            return this.nameUrlField;
        }
        set {
            this.nameUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string realm {
        get {
            return this.realmField;
        }
        set {
            this.realmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string realmUrl {
        get {
            return this.realmUrlField;
        }
        set {
            this.realmUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class pageGuildInfoGuildHeaderEmblem {
    
    private string emblemBackgroundField;
    
    private string emblemBorderColorField;
    
    private string emblemBorderStyleField;
    
    private string emblemIconColorField;
    
    private string emblemIconStyleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string emblemBackground {
        get {
            return this.emblemBackgroundField;
        }
        set {
            this.emblemBackgroundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string emblemBorderColor {
        get {
            return this.emblemBorderColorField;
        }
        set {
            this.emblemBorderColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string emblemBorderStyle {
        get {
            return this.emblemBorderStyleField;
        }
        set {
            this.emblemBorderStyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string emblemIconColor {
        get {
            return this.emblemIconColorField;
        }
        set {
            this.emblemIconColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string emblemIconStyle {
        get {
            return this.emblemIconStyleField;
        }
        set {
            this.emblemIconStyleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class pageGuildInfoGuildMessages {
    
    private string infoField;
    
    private string motdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string info {
        get {
            return this.infoField;
        }
        set {
            this.infoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string motd {
        get {
            return this.motdField;
        }
        set {
            this.motdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class pageGuildInfoGuildRanksRank {
    
    private string idField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class pageGuildInfoGuildBank {
    
    private pageGuildInfoGuildBankBagsBag[] bagsField;
    
    private pageGuildInfoGuildBankBanklogs[] banklogsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("bag", typeof(pageGuildInfoGuildBankBagsBag), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public pageGuildInfoGuildBankBagsBag[] bags {
        get {
            return this.bagsField;
        }
        set {
            this.bagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("banklogs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public pageGuildInfoGuildBankBanklogs[] banklogs {
        get {
            return this.banklogsField;
        }
        set {
            this.banklogsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class pageGuildInfoGuildBankBagsBag {
    
    private string iconField;
    
    private string idField;
    
    private string nameField;
    
    private string viewableField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string viewable {
        get {
            return this.viewableField;
        }
        set {
            this.viewableField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class pageGuildInfoGuildBankBanklogs {
    
    private pageGuildInfoGuildBankBanklogsBanklog[] banklogField;
    
    private string groupField;
    
    private string nextField;
    
    private string nowField;
    
    private string prevField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("banklog", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public pageGuildInfoGuildBankBanklogsBanklog[] banklog {
        get {
            return this.banklogField;
        }
        set {
            this.banklogField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string next {
        get {
            return this.nextField;
        }
        set {
            this.nextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string now {
        get {
            return this.nowField;
        }
        set {
            this.nowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prev {
        get {
            return this.prevField;
        }
        set {
            this.prevField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class pageGuildInfoGuildBankBanklogsBanklog {
    
    private pageGuildInfoGuildBankBanklogsBanklogItem[] itemField;
    
    private string dtabField;
    
    private int moneyField;
    
    private string otabField;
    
    private string playerField;
    
    private string rankField;
    
    private long tsField;
    
    private int typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public pageGuildInfoGuildBankBanklogsBanklogItem[] item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dtab {
        get {
            return this.dtabField;
        }
        set {
            this.dtabField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int money {
        get {
            return this.moneyField;
        }
        set {
            this.moneyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string otab {
        get {
            return this.otabField;
        }
        set {
            this.otabField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string player {
        get {
            return this.playerField;
        }
        set {
            this.playerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rank {
        get {
            return this.rankField;
        }
        set {
            this.rankField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long ts {
        get {
            return this.tsField;
        }
        set {
            this.tsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class pageGuildInfoGuildBankBanklogsBanklogItem {
    
    private int countField;
    
    private string iconField;
    
    private int idField;
    
    private string nameField;
    
    private int qiField;
    
    private string subtypeField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int qi {
        get {
            return this.qiField;
        }
        set {
            this.qiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string subtype {
        get {
            return this.subtypeField;
        }
        set {
            this.subtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private page[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("page")]
    public page[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
