//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class wowhead {
    
    private Item itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Item Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }

    public wowhead() { }

    public object[] ToObjectArray()
    {
        return new object[] { 
            itemsField.id, 
            itemsField.name, 
            //itemsField.icon, 
            itemsField.itemClass.Value, 
            itemsField.itemSubClass.Value, 
            itemsField.level, 
            itemsField.quality.id, 
            itemsField.sellprice, 
            itemsField.buyprice, 
            itemsField.avgbuyout, 
            itemsField.weight, 
            itemsField.updated};
    }

    public static System.Data.DataTable CreateTable(string tableName)
    {
        System.Data.DataTable table = new System.Data.DataTable(tableName);

        table.Columns.Add("id", typeof(int));
        table.Columns.Add("Name", typeof(string)); //I should really look up expressions for datacolumn.
        //table.Columns.Add("Icon", typeof(string));
        table.Columns.Add("Class", typeof(string));
        table.Columns.Add("Subclass", typeof(string));
        table.Columns.Add("Level", typeof(int));
        table.Columns.Add("Quality", typeof(int));
        table.Columns.Add("Sell Price", typeof(int));
        table.Columns.Add("Buy Price", typeof(int));
        table.Columns.Add("Avg Buyout", typeof(int));
        table.Columns.Add("Weight", typeof(double));
        table.Columns.Add("Updated", typeof(DateTime));

        return table;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public class Item {
    
    private string nameField;
    
    private int levelField;
    
    private string htmlTooltipField;
    
    private string jsonField;
    
    private string jsonEquipField;
    
    private string linkField;
    
    private Quality qualityField;
    
    private ItemClass classField;
    
    private ItemSubclass subclassField;
    
    private Icon iconField;
    
    private InventorySlot inventorySlotField;

    private CreatedBySpell[] createdByField;
    
    private int idField;

    /* Data for item weighting */
    private int buypriceField;
    private int sellpriceField;
    private int avgbuyoutField;
    private double weightField;

    private DateTime updatedField;

    public static double weightModifier = 0.01;

    #region Getters & Setters

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string name
    {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string htmlTooltip {
        get {
            return this.htmlTooltipField;
        }
        set {
            this.htmlTooltipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string json {
        get {
            return this.jsonField;
        }
        set {
            this.jsonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string jsonEquip {
        get {
            return this.jsonEquipField;
        }
        set {
            this.jsonEquipField = value;
            
            //Get the vendor, buy and avgBuyout price
            string[] str = value.Split(',');
            foreach (string temp in str)
            {
                string[] str2 = temp.Split(':');
                if(str2[0] == "buyprice")
                {
                    this.buypriceField = int.Parse(str2[1]);
                } 
                else if (str2[0] == "sellprice")
                {
                    this.sellpriceField = int.Parse(str2[1]);
                }
                else if (str2[0] == "avgbuyout")
                {
                    this.avgbuyoutField = int.Parse(str2[1]);
                }
            }
            
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("quality", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public Quality quality {
        get {
            return this.qualityField;
        }
        set {
            this.qualityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("class", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public ItemClass itemClass {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("subclass", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public ItemSubclass itemSubClass {
        get {
            return this.subclassField;
        }
        set {
            this.subclassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("icon", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public Icon icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("inventorySlot", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public InventorySlot inventorySlot {
        get {
            return this.inventorySlotField;
        }
        set {
            this.inventorySlotField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("spell", typeof(CreatedBySpell), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public CreatedBySpell[] createdBy {
        get {
            return this.createdByField;
        }
        set {
            this.createdByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    [System.Xml.Serialization.XmlIgnore]
    public int sellprice
    {
        get { return this.sellpriceField; }
        set { this.sellpriceField = value; }
    }

    [System.Xml.Serialization.XmlIgnore]
    public int buyprice
    {
        get { return this.buypriceField; }
        set { this.buypriceField = value; }
    }

    [System.Xml.Serialization.XmlIgnore]
    public int avgbuyout
    {
        get { return this.avgbuyoutField; }
        set { this.avgbuyoutField = value; }
    }

    public double weight
    {
        get { return this.weightField; }
        set { this.weightField = value; }
    }
    
    [System.Xml.Serialization.XmlIgnore]
    public DateTime updated
    {
        get { return this.updatedField; }
        set { this.updatedField = value; }
    }

    #endregion

    public double SetDefaultWeight()
    { return this.weightField = avgbuyoutField * weightModifier; }

    public Item() { 
	}

}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public class Quality {
    
    private int idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public class ItemClass {
    
    private int idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public class ItemSubclass {
    
    private int idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public class Icon {
    
    private int displayIdField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int displayId {
        get {
            return this.displayIdField;
        }
        set {
            this.displayIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public class InventorySlot {
    
    private int idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public class CreatedBySpell {
    
    private Reagent[] reagentField;
    
    private int idField;
    
    private string nameField;
    
    private string iconField;
    
    private int minCountField;
    
    private int maxCountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("reagent", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Reagent[] reagent {
        get {
            return this.reagentField;
        }
        set {
            this.reagentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int minCount {
        get {
            return this.minCountField;
        }
        set {
            this.minCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int maxCount {
        get {
            return this.maxCountField;
        }
        set {
            this.maxCountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public class Reagent {
    
    private int idField;
    
    private string nameField;
    
    private int qualityField;
    
    private string iconField;
    
    private int countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int quality {
        get {
            return this.qualityField;
        }
        set {
            this.qualityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}
